on:
    pull_request:
        paths:
            - 'src/**'
            - 'tests/**'
            - '.github/workflows/**'

    push:
        branches:
            - develop
            - master

name: Test

env:
    SYMFONY_DEPRECATIONS_HELPER: max[self]=0
    TARGET: test
    UPSTREAM_URL: https://github.com/sonata-project/SonataAdminBundle.git
    PHPUNIT_VERSION: 8
    PHP_EXTENSIONS: "json" # just for testing now
    PHP_INI_VALUES: "memory_limit=3072M"

jobs:
    test:
        name: PHP ${{ matrix.php-version }} + ${{ matrix.variant }}

        runs-on: ubuntu-16.04 # xenial

        strategy:
            matrix:
                php-version:
                    - "7.3"
                variant:
                    - "SYMFONY=4.4.*"
                    - "SYMFONY='dev-master as 4.4.x-dev'"
                    - "SONATA_CORE=3.*"
                    - "SONATA_CORE='dev-master as 3.x-dev'"
                    - "SONATA_BLOCK=3.*"
                    - "SONATA_BLOCK='dev-master as 3.x-dev'"
                    - "SYMFONY_DEPRECATIONS_HELPER=0"

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2.0.0

            - name: "Install PHP with extensions"
              uses: "shivammathur/setup-php@v1"
              with:
                  coverage: "none"
                  extensions: "${{ env.PHP_EXTENSIONS }}"
                  php-version: "${{ matrix.php-version }}"
                  ini-values: "${{ env.PHP_INI_VALUES }}"

            - name: "Install dependencies with composer"
              run: composer update --prefer-dist --no-interaction --prefer-stable --no-progress

            - run: export ${{ matrix.variant }}

            - run: sh ./travis/before_install_test.sh

            - name: "Setup PHPunit"
              run: |
                  mkdir bin
                  wget "https://phar.phpunit.de/phpunit-${{ env.PHPUNIT_VERSION }}.phar" --output-document="bin/phpunit"
                  chmod u+x "bin/phpunit"

            - name: "Run tests via PHPUnit"
              run: make test
