on:
    pull_request:
        paths:
            - 'src/**'
            - 'tests/**'
            - '.github/workflows/**'

    push:
        branches:
            - develop
            - master

name: Test

env:
    SYMFONY_DEPRECATIONS_HELPER: max[self]=0
    PHPUNIT_VERSION: 8
    PHP_EXTENSIONS: "json" # just for testing now
    PHP_INI_VALUES: "memory_limit=3072M"

jobs:
    test:
        name: PHP ${{ matrix.php-version }} + --prefer-lowest

        runs-on: ubuntu-16.04 # xenial

        strategy:
            matrix:
                php-version:
                    - "7.2"
                    - "7.3"
                    - "7.4"

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2.0.0

            - name: "Install PHP with extensions"
              uses: "shivammathur/setup-php@v1"
              with:
                  coverage: "none"
                  extensions: "${{ env.PHP_EXTENSIONS }}"
                  php-version: "${{ matrix.php-version }}"
                  ini-values: "${{ env.PHP_INI_VALUES }}"
                  tools: phpunit:8.5.2

            - run: composer update --prefer-dist --no-interaction --prefer-stable --no-progress --prefer-lowest

            - name: "Run tests via PHPUnit"
              run: phpunit -c phpunit.xml.dist
